CREATE TABLE IF NOT EXISTS
	SENSORS (
		ID BIGINT AUTO_INCREMENT PRIMARY KEY,
		ADDRESS VARCHAR(30) NOT NULL,
		LABEL VARCHAR(30) NOT NULL,
		DESCRIPTION VARCHAR,
		SENSOR_TYPE VARCHAR(20) NOT NULL
	);
CREATE INDEX IF NOT EXISTS SENSORS_ADDRESS ON SENSORS(ADDRESS);
CREATE INDEX IF NOT EXISTS SENSORS_LABEL ON SENSORS(LABEL);

CREATE TABLE IF NOT EXISTS
	ACTUATORS (
		ID BIGINT AUTO_INCREMENT PRIMARY KEY,
		ADDRESS VARCHAR(30) NOT NULL,
		LABEL VARCHAR(30) NOT NULL,
		DESCRIPTION VARCHAR,
		ACTUATOR_TYPE VARCHAR(20) NOT NULL
	);
CREATE INDEX IF NOT EXISTS ACTUATORS_ADDRESS ON ACTUATORS(ADDRESS);
CREATE INDEX IF NOT EXISTS ACTUATORS_LABEL ON ACTUATORS(LABEL);

CREATE TABLE IF NOT EXISTS
	ADJUSTABLE_ACTUATORS (
		ACTUATOR BIGINT NOT NULL,
		MIN_VALUE DOUBLE NOT NULL,
		MAX_VALUE DOUBLE NOT NULL,
		CHANGE_STEP DOUBLE NOT NULL,
		DEFAULT_VALUE DOUBLE NOT NULL,
		FOREIGN KEY(ACTUATOR) REFERENCES ACTUATORS(ID)
	);

CREATE TABLE IF NOT EXISTS
	SIGNALING_ELEMENT (
		ID BIGINT AUTO_INCREMENT PRIMARY KEY,
		DEVICE_ADDRESS VARCHAR(30) NOT NULL,
		ACTUATOR_ADDRESS VARCHAR(30),
		LABEL VARCHAR(30) NOT NULL,
		ENABLED BOOLEAN NOT NULL
	);
CREATE INDEX IF NOT EXISTS SIGNALING_ELEMENT_ADDRESS ON SIGNALING_ELEMENT(DEVICE_ADDRESS);

CREATE TABLE IF NOT EXISTS
	TRIGGER_CONDITION (
		ID BIGINT AUTO_INCREMENT PRIMARY KEY,
		EXPRESSION VARCHAR NOT NULL
	);

CREATE TABLE IF NOT EXISTS
	ACTUATOR_TRIGGER (
		ID BIGINT AUTO_INCREMENT PRIMARY KEY,
		NAME VARCHAR(30) NOT NULL,
		ENABLED BOOLEAN NOT NULL,
        ACTUATOR_ADDRESS VARCHAR(30) NOT NULL,
        ACTUATOR_VALUE BOOLEAN NOT NULL,
        CONDITION BIGINT NOT NULL,
        FOREIGN KEY(CONDITION) REFERENCES TRIGGER_CONDITION(ID)
	);

CREATE TABLE IF NOT EXISTS
	IMAGES (
		ID BIGINT AUTO_INCREMENT PRIMARY KEY,
		FILE_NAME VARCHAR NOT NULL,
		FILE_CONTENT BLOB NOT NULL,
		UNIQUE KEY FILE_NAME_UNIQUE (FILE_NAME)
	);
CREATE INDEX IF NOT EXISTS IMAGES_FILE_NAME ON IMAGES(FILE_NAME);

CREATE TABLE IF NOT EXISTS
	SPACES (
		ID BIGINT AUTO_INCREMENT PRIMARY KEY,
		NAME VARCHAR(30) NOT NULL,
		IMAGE BIGINT NOT NULL,
		FOREIGN KEY(IMAGE) REFERENCES IMAGES(ID)
	);




